#!/usr/bin/env python
import os
import glob
files = glob.glob('*.html')

for fn in files:
    content = open(fn).read()
    if content[0:3] == '---': continue
    f = open(fn, 'w')
    print('---\nlayout: default\n---', file=f)
    print(content, file=f)

config = open('_config.yml').read().split('\n')
titleLine = list(filter(lambda x: 'title:' in x, config))[0]
title = titleLine.replace('title: ', '')

f = open('_includes/header.html', 'w')
h = ('<div>\n'
     '  <div id="header">%s</div>\n'
     '  <div id="description">by Patrick Breheny, %s</div>\n'
     # '  <h1>%s</h1>\n'
     # '  <p id="description">by Patrick Breheny, %s</p>\n'
     '</div>')
from datetime import date
print(h % (title, date.today()), file=f)
f.close()

os.system('jekyll build')
