#' Render an rmd file built within the html package template
#' 
#' @param f      File to render
#' @param purl   Deposit .R files in _R folder?  Default is true.

render_html <- function(f, purl=TRUE) {
  if (!file.exists(f)) stop("file '", f, "' does not exist!")
  tmp <- stringr::str_split(f, '\\.')[[1]]
  base <- stringr::str_split(tmp[1], '\\/')[[1]]
  base_dir <- paste(base[-length(base)], collapse='/')
  out_dir <- paste0(base_dir, '/_site')
  handle <- base[length(base)]
  ext <- tmp[2]
  
  if (purl) {
    # Create purl directory if it does not exist
    purl_dir <- paste0(base_dir, '/_R')
    if (!dir.exists(purl_dir)) dir.create(purl_dir)
    
    # Erase old R file
    Rfile <- paste0(purl_dir, '/', handle, '.R')
    if (file.exists(Rfile)) file.remove(Rfile)
    knitr::purl(f, documentation=1L, output=Rfile)
    
    # Restyle R comments
    rlines <- readLines(Rfile)
    ind <- grep("## ----", rlines)
    x <- rlines[ind]
    x <- gsub("## ----", "# ", x, fixed=TRUE)
    x <- gsub("\\,.*", "", x)
    x <- gsub("___", ": ", x)
    x <- gsub("__", ", ", x)
    x <- gsub("_", " ", x)
    x <- gsub("-+-", "", x)
    rlines[ind] <- x
    ind <- min(which(rlines!=""))
    topline <- paste0('THIS FILE WAS GENERATED BY ', f, ': DO NOT EDIT BY HAND')
    x <- paste(c(topline, '', rlines), collapse="\n")
    cat(x, file=Rfile)
  }
  yaml <- paste0(base_dir, '/_site.yml')
  cat('yaml:', yaml, file.exists(yaml), '\n')
  
  rmarkdown::render(f, output_dir=out_dir, knit_root_dir=getwd(), output_yaml=yaml)
}
