#' Render an rmd file built within the html package template
#' 
#' @param f        File to render (character)
#' @param purl     Deposit .r files in _r folder? (default: `FALSE`)
#' @param quiet    As in `rmarkdown::render()`. (default: `FALSE`)
#' @param force    By default, `render_page()` requires the folders `docs` or `web` to exist if multiple `.html` files are present. To override this behavior and force rendering, set `force=TRUE`.
#' 
#' @export

render_page <- function(f, purl=FALSE, quiet=FALSE, force=FALSE) {

  # Process input file location
  if (!file.exists(f)) stop("file '", f, "' does not exist!")
  ext <- tools::file_ext(f)
  base_dir <- dirname(f)
  handle <- tools::file_path_sans_ext(basename(f))
  
  # Decide on output file location
  if (base_dir == 'web') {
    out_dir <- paste0(base_dir, '/_site')
    if (!dir.exists(out_dir)) dir.create(out_dir)
  } else if (dir.exists(paste0(base_dir, '/docs'))) {
    out_dir <- paste0(base_dir, '/docs')
  } else if (length(list.files(base_dir, '*.rmd', ignore.case=TRUE)) > 1 && force == FALSE) {
    stop('No!', call. = FALSE)
  } else {
    out_dir <- base_dir
  }

  if (purl) {
    
    # Set destination
    if (out_dir == base_dir) {
      Rfile <- paste0(base_dir, '/', handle, '.r')
    } else {
      Rdir <- paste0(base_dir, '/_r')
      Rfile <- paste0(Rdir, '/', handle, '.r')
      if (!dir.exists(Rdir)) dir.create(Rdir)
    }
    
    # Purl
    if (file.exists(Rfile)) file.remove(Rfile)
    knitr::purl(f, documentation=1L, output=Rfile, quiet=quiet)

    # Restyle R comments
    rlines <- readLines(Rfile)
    ind <- grep("## ----", rlines)
    x <- rlines[ind]
    x <- gsub("## ----", "# ", x, fixed=TRUE)
    x <- gsub("\\,.*", "", x)
    x <- gsub("___", ": ", x)
    x <- gsub("__", ", ", x)
    x <- gsub("_", " ", x)
    x <- gsub("-+-", "", x)
    x <- gsub("#  ", "# ", x, fixed=TRUE)
    rlines[ind] <- x
    ind <- min(which(rlines!=""))
    topline <- paste0('THIS FILE WAS GENERATED BY ', f, ': DO NOT EDIT BY HAND')
    x <- paste(c(topline, '', rlines), collapse="\n")
    cat(x, file=Rfile)
  }
  
  # update footer if applicable
  if (file.exists('web/_include/footer.html') & file.exists('web/_site.yml')) {
    update_footer('web/_include/footer.html', 'web/_site.yml')
  }

  # Render
  out <- catchWarning(rmarkdown::render(f, output_dir=out_dir, knit_root_dir=getwd(), quiet=quiet, envir=new.env(parent=.GlobalEnv)))
  skip <- stringr::str_detect(as.character(out$warning), "MathJax doesn't work with self_contained")
  if (length(out$warning[!skip])) warning(out$warning[!skip])
  if (inherits(out$value, 'error')) stop(out$value$message)
}
