#' Render an rmd file built within the html package template
#' 
#' @param f        File to render
#' @param web      For website; assume a workflow in which `f="web/index.rmd"` and output to `web/_site` and `web/_R`
#' @param purl     Deposit .R files in _R folder?  Default is FALSE.
#' @param quiet    As in `rmarkdown::render()`; Default is FALSE.
#' 
#' @export

render_page <- function(f, web=FALSE, purl=FALSE, quiet=FALSE) {

  # Process input file location
  if (!file.exists(f)) stop("file '", f, "' does not exist!")
  path <- stringr::str_split(f, '\\.')[[1]] %>%
    magrittr::extract2(1) %>%
    stringr::str_split('\\/') %>%
    magrittr::extract2(1)
  base_dir <- paste(path[-length(path)], collapse='/')
  if (base_dir == '') base_dir <- '.'
  out_dir <- paste0(base_dir, ifelse(web, '/_site', ''))
  handle <- path[length(path)]
  ext <- stringr::str_split(f, '\\.')[[1]][2] %>% stringr::str_to_lower()
  
  if (purl) {
    
    # Erase old R file
    if (web) {
      Rdir <- paste0(base_dir, '/_R')
      Rfile <- paste0(Rdir, '/', handle, '.R')
      if (!dir.exists(Rdir)) dir.create(Rdir)
    } else {
      Rfile <- paste0(base_dir, '/', handle, '.R')
    }
    if (file.exists(Rfile)) file.remove(Rfile)
    knitr::purl(f, documentation=1L, output=Rfile, quiet=quiet)

    # Restyle R comments
    rlines <- readLines(Rfile)
    ind <- grep("## ----", rlines)
    x <- rlines[ind]
    x <- gsub("## ----", "# ", x, fixed=TRUE)
    x <- gsub("\\,.*", "", x)
    x <- gsub("___", ": ", x)
    x <- gsub("__", ", ", x)
    x <- gsub("_", " ", x)
    x <- gsub("-+-", "", x)
    x <- gsub("#  ", "# ", x, fixed=TRUE)
    rlines[ind] <- x
    ind <- min(which(rlines!=""))
    if (web) {
      topline <- paste0('THIS FILE WAS GENERATED BY ', f, ': DO NOT EDIT BY HAND')
      x <- paste(c(topline, '', rlines), collapse="\n")
      cat(x, file=Rfile)
    } else {
      cat(rlines, file=Rfile, sep='\n')
    }
  }
  
  # update footer if applicable
  if (web && file.exists('web/_include/footer.html') & file.exists('web/_site.yml')) {
    update_footer('web/_include/footer.html', 'web/_site.yml')
  }

  # Render
  out <- catchWarning(rmarkdown::render(f, output_dir=out_dir, knit_root_dir=getwd(), quiet=quiet, envir=new.env(parent=.GlobalEnv)))
  skip <- stringr::str_detect(as.character(out$warning), "MathJax doesn't work with self_contained")
  if (length(out$warning[!skip])) warning(out$warning[!skip])
}
